### ISSUE TITLE
3D Gizmo's for Glue Anchors not being changed on click.

### ISSUE THREAD

**Issue by jnitafan** [Riordan-DC/GlueAddon#1]
### Godot Version

v4.3.stable.official

### System Information

Windows 11

### Addon Version

4.x
commit: [f989a6729711a24f66fa8f1c909c8e322321a6d7]

### Issue description

Currently the handle gizmos does not flip the setting for the node to be an anchor or a free node.

This can be fixed by editing the script in GraphGizmo.gd:
```
func _commit_handle(index: int, _secondary, restore, cancel: bool=false):
	var node = get_node_3d()
	if node._graph != null:
		node._graph._nodes[index].anchor = !node._graph._nodes[index].anchor
		#print("HANDLE UPDATE GRAPH NODE AT INDEX: %d [ANCHOR = %s]" % [index, node._graph._nodes[index].anchor])
```
to
```
func _begin_handle_action(index, _secondary):
	var node = get_node_3d()
	if node._graph != null:
		node._graph._nodes[index].anchor = !node._graph._nodes[index].anchor
		#print("HANDLE UPDATE GRAPH NODE AT INDEX: %d [ANCHOR = %s]" % [index, node._graph._nodes[index].anchor])
```

(Side note: This is probably the best destruction addon and it is criminally underrated. I'm going to be modifying it to my own usage)

**Comment by Riordan-DC** [comment]
Your change is implemented in #2
 
(side note: thanks so much! tell ur friends lol)
